name: drive_adviser
description: A drive health app
publish_to: "Schrock Innovations, Inc"
version: 1.6.4

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pdf: ^3.10.4
  html: ^0.15.4
  process_run: ^0.13.1
  open_file: ^3.3.2
  path_provider: ^2.1.1
  flutter_acrylic: ^1.1.3
  bitsdojo_window: ^0.1.5
  url_launcher: ^6.1.14
  http: ^0.13.6
  msix: ^3.16.1
  launch_at_startup: ^0.2.2
  package_info_plus: ^3.1.2
  printing: ^5.11.0
  intl: ^0.18.1
  get: ^4.6.6
  auto_updater: ^0.1.7
  windows_single_instance: ^1.0.0
  shell: ^2.0.0
  xml: ^6.3.0
  ini: ^2.1.0
  material_scrollbar: ^0.0.1
  flutter_window: ^1.0.0
  window_manager: ^0.3.7
  email_validator: ^2.1.17
  quiver: ^3.2.1
  path: ^1.8.3
  file_selector: ^1.0.3
  system_tray: ^2.0.3
  auto_size_text: ^3.0.0
  battery_plus: ^5.0.1
  ffi: ^2.1.2
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/

#msix_config:
#  display_name: Drive Adviser
#  publisher_display_name: Schrock Innovations Inc
#  identity_name: SchrockInnovationsInc.driveAdviser
#  app_installer: #<-- app installer configuration
#    publish_folder_path: C:\Users\Alfonso
#    hours_between_update_checks: 0
#    automatic_background_task: true
#    update_blocks_activation: true
#    show_prompt: true
#    force_update_from_any_version: false
#  msix_version: 1.6.4.0
#  certificate_path: C:\Users\Alfonso\StudioProjects\sophosFlutter\certificates\schrockInnovations3.pfx
#  certificate_password: Vcuz3kgOnEQYlL1A
#  publisher: CN="Schrock Innovations, Inc", O="Schrock Innovations, Inc", S=Nebraska, C=US, OID.2.5.4.15=Private Organization, OID.1.3.6.1.4.1.311.60.2.1.2=Nebraska, OID.1.3.6.1.4.1.311.60.2.1.3=US, SERIALNUMBER=10008831
#  logo_path: C:\driveAdviserLogoPin.png
#  start_menu_icon_path: C:\driveAdviserLogoPin.png
#  tile_icon_path: C:\driveAdviserLogoPin.png
#  languages: en-us
#  #  capabilities: "internetClient"
#  capabilities: "runFullTrust"
#  signtool_options: /fd SHA256 /f "C:\Users\Alfonso\StudioProjects\sophosFlutter\certificates\schrockInnovations3.pfx" /p Vcuz3kgOnEQYlL1A
#  sign_msix: true
msix_config:
  display_name: Drive Adviser
  publisher_display_name: Denis
  identity_name: Denis.DA
  msix_version: 1.6.4.0
  languages: en-us
  capabilities: "runFullTrust"